export const BOOKS = {
    GEN: 'Genesis',
    GENESIS: 'Genesis',
    EX: 'Exodus',
    EXO: 'Exodus',
    EXODUS: 'Exodus',
    LEV: 'Leviticus',
    LEVITICUS: 'Leviticus',
    NUM: 'Numbers',
    NUMBERS: 'Numbers',
    DEU: 'Deuteronomy',
    DEUT: 'Deuteronomy',
    DEUTERONOMY: 'Deuteronomy',
    JOS: 'Joshua',
    JOSH: 'Joshua',
    JOSHUA: 'Joshua',
    JDG: 'Judges',
    JUDG: 'Judges',
    JUDGES: 'Judges',
    RUT: 'Ruth',
    RUTH: 'Ruth',
    '1SA': '1 Samuel',
    '1SAM': '1 Samuel',
    '1SAMUEL': '1 Samuel',
    '2SA': '2 Samuel',
    '2SAM': '2 Samuel',
    '2SAMUEL': '2 Samuel',
    '1KI': '1 Kings',
    '1KINGS': '1 Kings',
    '2KI': '2 Kings',
    '2KINGS': '2 Kings',
    '1CH': '1 Chronicles',
    '1CHRON': '1 Chronicles',
    '1CHRONICLES': '1 Chronicles',
    '2CH': '2 Chronicles',
    '2CHRON': '2 Chronicles',
    '2CHRONICLES': '2 Chronicles',
    EZR: 'Ezra',
    EZRA: 'Ezra',
    NEH: 'Nehemiah',
    NEHEMIAH: 'Nehemiah',
    EST: 'Esther',
    ESTHER: 'Esther',
    JOB: 'Job',
    PS: 'Psalms',
    PSA: 'Psalms',
    PSALM: 'Psalms',
    PSALMS: 'Psalms',
    PRO: 'Proverbs',
    PROV: 'Proverbs',
    PROVERBS: 'Proverbs',
    ECC: 'Ecclesiastes',
    ECCLES: 'Ecclesiastes',
    ECCLESIASTES: 'Ecclesiastes',
    SNG: 'Song of Solomon',
    SONG: 'Song of Solomon',
    ISA: 'Isaiah',
    ISAIAH: 'Isaiah',
    JER: 'Jeremiah',
    JEREMIAH: 'Jeremiah',
    LAM: 'Lamentations',
    LAMENTATIONS: 'Lamentations',
    EZK: 'Ezekiel',
    EZEK: 'Ezekiel',
    EZEKIEL: 'Ezekiel',
    DAN: 'Daniel',
    DANIEL: 'Daniel',
    HOS: 'Hosea',
    HOSEA: 'Hosea',
    JOL: 'Joel',
    JOEL: 'Joel',
    AMO: 'Amos',
    AMOS: 'Amos',
    OBA: 'Obadiah',
    OBAD: 'Obadiah',
    OBADIAH: 'Obadiah',
    JON: 'Jonah',
    JONAH: 'Jonah',
    MIC: 'Micah',
    MICAH: 'Micah',
    NAM: 'Nahum',
    NAHUM: 'Nahum',
    HAB: 'Habakkuk',
    HABAKKUK: 'Habakkuk',
    ZEP: 'Zephaniah',
    ZEPH: 'Zephaniah',
    ZEPHANIAH: 'Zephaniah',
    HAG: 'Haggai',
    HAGGAI: 'Haggai',
    ZEC: 'Zechariah',
    ZECH: 'Zechariah',
    ZECHARIAH: 'Zechariah',
    MAL: 'Malachi',
    MALACHI: 'Malachi',
    MAT: 'Matthew',
    MATT: 'Matthew',
    MATTHEW: 'Matthew',
    MRK: 'Mark',
    MARK: 'Mark',
    LUK: 'Luke',
    LUKE: 'Luke',
    JHN: 'John',
    JOHN: 'John',
    ACT: 'Acts',
    ACTS: 'Acts',
    ROM: 'Romans',
    ROMANS: 'Romans',
    '1CO': '1 Corinthians',
    '1COR': '1 Corinthians',
    '1CORINTHIANS': '1 Corinthians',
    '2CO': '2 Corinthians',
    '2COR': '2 Corinthians',
    '2CORINTHIANS': '2 Corinthians',
    GAL: 'Galatians',
    GALATIANS: 'Galatians',
    EPH: 'Ephesians',
    EPHESIANS: 'Ephesians',
    PHP: 'Philippians',
    PHIL: 'Philippians',
    PHILIPPIANS: 'Philippians',
    COL: 'Colossians',
    COLOSSIANS: 'Colossians',
    '1TH': '1 Thessalonians',
    '1THESS': '1 Thessalonians',
    '1THESSALONIANS': '1 Thessalonians',
    '2TH': '2 Thessalonians',
    '2THESS': '2 Thessalonians',
    '2THESSALONIANS': '2 Thessalonians',
    '1TI': '1 Timothy',
    '1TIM': '1 Timothy',
    '1TIMOTHY': '1 Timothy',
    '2TI': '2 Timothy',
    '2TIM': '2 Timothy',
    '2TIMOTHY': '2 Timothy',
    TIT: 'Titus',
    TITUS: 'Titus',
    PHM: 'Philemon',
    PHILEM: 'Philemon',
    PHILEMON: 'Philemon',
    HEB: 'Hebrews',
    HEBREWS: 'Hebrews',
    JAS: 'James',
    JAMES: 'James',
    '1PE': '1 Peter',
    '1PET': '1 Peter',
    '1PETER': '1 Peter',
    '2PE': '2 Peter',
    '2PET': '2 Peter',
    '2PETER': '2 Peter',
    '1JN': '1 John',
    '1JOHN': '1 John',
    '2JN': '2 John',
    '2JOHN': '2 John',
    '3JN': '3 John',
    '3JOHN': '3 John',
    JUD: 'Jude',
    JUDE: 'Jude',
    REV: 'Revelation',
    REVELATION: 'Revelation',
};
