graph TD
    %% God to Abraham
    God
    ---
    Adam
    ---
    Seth
    ---
    Enosh
    ---
    Kenan
    ---
    Mahalalel
    ---
    Jared
    ---
    Enoch
    ---
    Methuselah
    ---
    Lamech
    ---
    Noah
    ---
    Shem
    ---
    Arpachshad
    ---
    Shelah
    ---
    Eber
    ---
    Peleg
    ---
    Reu
    ---
    Serug
    ---
    Nahor
    ---
    Terah
    ---
    %% Abrham to David
    Abraham["
    Abraham
    God's Covenant
    "]
    ---
    Isaac
    ---
    Jacob
    ---
    Judah
    ---
    Perez
    ---
    Hezron
    ---
    Ram
    ---
    Amminadab
    ---
    Nahshon
    ---
    Salmon
    ---
    Boaz
    ---
    Obed
    ---
    Jessie
    ---
    %% David to Jehoiachin
    David
    ---
    Solomon
    ---
    Rehoboam
    ---
    Abijah
    ---
    Asa
    ---
    Jehoshaphat
    ---
    Joram
    ---
    Ahaziah["(Ahaziah)"]
    ---
    Joash["(Joash)"]
    ---
    Amaziah["(Amaziah)"]
    ---
    Uzziah
    ---
    Jotham
    ---
    Ahaz
    ---
    Hezekiah
    ---
    Manasseh
    ---
    Amon
    ---
    Josiah
    ---
    Jehoiakim["(Jehoiakim)"]
    ---
    %% Jehoiachin to St. Joseph
    Jehoiachin["
    Jehoiachin
    <em>aka Jeconiah or Coniah</em>
    Babylonian Exile
    "]
    Jehoiachin --- Pedaiah["(Pedaiah)"]
    Jehoiachin --- |legal| Shealtiel
    Pedaiah --- |legal| Zerubbabel
    Shealtiel --- |biological| Zerubbabel
    Zerubbabel
    ---
    Abiud
    ---
    Eliakim
    ---
    Azor
    ---
    Zadok
    ---
    Achim
    ---
    Eluid
    ---
    Eleazar
    ---
    Matthan
    ---
    Jacob2[Jacob] --- |biological| Joseph[St. Joseph]
    %% David to St. Mary
    David["
    David
    God's King
    "]
    ---
    Nathan
    ---
    Mattatha
    ---
    Menna
    ---
    Melea
    ---
    Eliakim2[Eliakim]
    ---
    Jonam
    ---
    Joseph2[Joseph]
    ---
    Judah2[Judah]
    ---
    Simeon
    ---
    Levi
    ---
    Matthat
    ---
    Jorim
    ---
    Eliezer
    ---
    Joshua
    ---
    Er
    ---
    Elmadam
    ---
    Cosam
    ---
    Addi
    ---
    Melchi
    ---
    Neri --- |biological| Shealtiel
    Zerubbabel --- Rhesa
    ---
    Joanan
    ---
    Joda
    ---
    Josech
    ---
    Semein
    ---
    Mattathias
    ---
    Maath
    ---
    Naggai
    ---
    Esli
    ---
    Nahum
    ---
    Amos
    ---
    Mattathias2[Mattathias]
    ---
    Joseph3[Joseph]
    ---
    Jannai
    ---
    Melchi2[Melchi]
    ---
    Levi2[Levi]
    ---
    Matthat2[Matthat]
    ---
    Heli --- |legal| Joseph
    Levi2 --- Panther
    ---
    Barpanther
    ---
    Joachim[St. Joachim] --- Mary[St. Mary]
    Anne[St. Anne] --- Mary
    %% St. Mary to Jesus
    Mary
    ---
    Jesus["
    Jesus
    God's Son
    "]
    Joseph --- Jesus
