graph TD
    %% David
    David

    %% Jeroboam
    Jeroboam["
    Jeroboam
    <small>Of Ephraim, promised 10 tribes, flees to Egypt.</small>
    "]
    ---
    JeroboamReturn["
    <small>Returns from Egypt.</small>
    "]

    %% David to Rehoboam
    David
    ---
    Solomon["
    Solomon
    <small>Kills his brother Adonijah and David's enemies, asks God for wisdom, builds temple, turns from God, oppresses Israel, leads people to idolatry.</small>
    "]
    ---
    Solomon2["
    <small>Looks to kill Jeroboam.</small>
    "]
    ---
    Rehoboam["
    Rehoboam
    <small>Threatens more oppression in Israel.</small>
    "]
    ---
    %% Kingdom split
    Split["
    <em>Kingdom Splits</em>
    <small>c. 930 BC</small>
    "]
    Split --- North["Northern Israel"]
    Split --- South["Southern Judah"]

    %% Northern Israel
    JeroboamReturn --- Split
    North
    ---
    JeroboamKing["
    Jeroboam
    <small>Lives in Tirzah, leads Israel to idolatry, death prophesied by Ahijah.</small>
    "]
    ---
    Nadab["
    Nadab
    <small>Walks in the way of his father.</small>
    "]
    ---
    Baasha["
    Baasha
    <small>Of Issachar, kills Nadab and house of Jeroboam, thus fulfilling Ahijah's prophecy.</small>
    "]
    ---
    BaashaRamah["
    <small>Captures Ramah.</small>
    "]
    ---
    BaashaJehu["
    <small>Leads Israel into idolatry, death prophesied by the prophet Jehu.</small>
    "]
    ---
    Elah["
    Elah
    <small>Leads Israel into idolatry.</small>
    "]
    ---
    Zimri["
    Zimri
    <small>Elah's servant, kills Elah and the house of Baasha, thus fulfilling the prophecy of Jehu.</small>
    "]
    ---
    Omri["
    Omri
    <small>Commander of army made king, besieges Tirzah and Zimri kills himself, overcomes Tibni, buys Samaria and lives there, does more evil than any other king before him.</small>
    "]
    ---
    Ahab["
    Ahab
    <small>Does more evil than any other king before him, marries Jezebel, worships Baal.</small>
    "]
    ---
    AhabJezebel["
    <small>Elijah prophesies drought, Jezebel kills the prophets, Obadiah saves 100 of them.</small>
    "]
    ---
    AhabElijah["
    <small>Elijah confronts Ahab and defeats false prophets, the Lord sends rain, Elijah flees Jezebel.</small>
    "]
    ---
    AhabSyria["
    <small>Trusts the Lord to defeat the Syrian army, but spares the king of Syria, death is prophesied by unnamed prophet.</small>
    "]
    ---
    AhabNaboth["
    <small>Ahab and Jezebel conspire against Naboth to kill him and steal his vineyard, Elijah prophesies death.</small>
    "]
    ---
    AhabAlliance["
    <small>Makes alliance with Jehoshaphat, wants to capture Ramoth-gilead from Syria, death prophesied by Micaiah, listens to false prophets, throws Micaiah in prison.</small>
    "]
    ---
    AhabDeath["
    <small>Disguises himself, dies in battle from random arrow that hits between his armor.</small>
    "]
    ---
    Ahaziah["
    Ahaziah
    <small>Does what is evil in the sight of the Lord like his mother and father, serves and worships Baal, provokes God to anger.</small>
    "]
    ---
    AhaziahDeath["
    <small>Falls through lattice in his upper chamber, sends men to inquire of Philistine god, Elijah prophesies death, fire consumes his men, brother Jehoram takes over since he has no son, dies in the 3rd year of Jehoram king of Judah's reign.</small>
    "]
    ---
    Jehoram["
    Jehoram
    <small>Gets rid of pillar of Baal, but still leads people to apostasy.</small>
    "]
    ---
    JehoramJehoshaphat["
    <small>Allies with Jehoshaphat and king of Edom to defeat Moab, Elisha prophesies water and Moab defeat.</small>
    "]
    ---
    JehoramSyria["
    <small>Syria captures Samaria, there is a famine, blames Elisha and threatens to behead him, Elisha promises food, God makes Syrians flee and provides food.</small>
    "]
    ---
    Jehu["
    Jehu
    <small>Elisha sends prophet to anoint him and tell him the prophecy of the destruction of the house of Ahab.</small>
    "]
    ---
    JehuJezreel["
    <small>Goes to Jezreel, kills Jehoram and puts him in Naboth's vineyard, chases Ahaziah to Samaria and kills him, goes back to Jezreel and has eunuchs throw Jezebel out of her window.</small>
    "]
    ---
    JehuElders["
    <small>Has elders of Samaria kill 70 sons of Ahab, destroys the rest of the house of Ahab, kills relatives of Ahaziah.</small>
    "]
    ---
    JehuFalseProphets["
    <small>Destroys house of Baal and false prophets, but leaves golden calves in Dan and Bethel, God promises his sons will reign to the fourth generation.</small>
    "]
    ---
    Jehoahaz["
    Jehoahaz
    <small>Does what is evil in the sight of the Lord, walks in the way of Jeroboam.</small>
    "]
    ---
    JehoahazSyria["
    <small>Oppressed by Syria, Lord has mercy and saves Israel, continues idolatry, army is whittled down.</small>
    "]
    ---
    Jehoash["
    Jehoash
    <small>Does what is evil in the sight of the Lord, walks in the way of Jeroboam.</small>
    "]
    ---
    JehoashElisha["
    <small>Elisha prophesies three victories over Syria, oppressed by Syria, Lord has mercy and saves Israel, takes back cities from Syria and defeats them three times as prophesied.</small>
    "]
    ---
    JehoashAmaziah["
    <small>Israel is enraged by Amaziah dismissing Israelite troops, troops raid Judah.</small>
    "]
    ---
    JehoashArmy["
    <small>Defeats Judah's army, captures Amaziah, breaks down wall in Jerusalem, plunders the temple and the king's house.</small>
    "]
    ---
    JeroboamII["
    Jeroboam II
    <small>Does what is evil in the sight of the Lord like Jeroboam, Israel falls into affliction as prophesied by Ahijah.</small>
    "]
    ---
    JeroboamIIMercy["
    <small>God has mercy on behalf of greater Israel and delivers them, restores northern border as prophesied by Jonah.</small>
    "]
    ---
    JeroboamIIFights["
    <small>Fights to restore Damascus and Hamat to Judah, becomes wealthy and oppresses the poor, death prophesied by Amos.</small>
    "]
    ---
    Zechariah["
    Zechariah
    <small>Does what is evil in the sight of the Lord, only reigns 6 months, killed by Shallum, fulfils the prophecy of the Lord regarding Jehu's sons reigning to the fourth generation.</small>
    "]
    ---
    Shallum["
    Shallum
    <small>Does what is evil in the sight of the Lord, only reigns 8 months, killed by Menahem.</small>
    "]
    ---
    Menahem["
    Menahem
    <small>Does what is evil in the sight of the Lord, sacks Tiphsah and kills pregnant women there, exacts silver from the men of Israel to placate king of Assyria.</small>
    "]
    ---
    Pekahiah["
    Pekahiah
    <small>Does what is evil in the sight of the Lord, his captain's son Pekah conspires against him with 50 men of Gilead who kill him in the citadel of the King's house.</small>
    "]
    ---
    Pekah["
    Pekah
    <small>Does what is evil in the sight of the Lord, king of Assyria captures Naphtali and takes people as captives to Assyria, Hoshea conspires against him and kills him.</small>
    "]
    ---
    Hoshea["
    Hoshea
    <small>Does what is evil in the sight of the Lord, becomes vassal to king of Assyria, imprisoned for supporting king of Egypt.</small>
    "]
    ---
    HosheaAssyria["
    <small>God gives Israel over to the king of Assyria who captures Samaria and exiles them from the land, they are scattered around Assyria, king of Assyria brings Babylonians to Samaria where syncretism becomes widely practiced.</small>
    "]

    %% Southern Judah
    South
    ---
    RehoboamKing["
    Rehoboam
    <small>Lives in Jerusalem, leads Judah to idolatry.</small>
    "]
    ---
    Abijah["
    Abijah
    <small>Trusts God to defeat Jeroboam's army, but then leads Judah back into idolatry.</small>
    "]
    ---
    Asa["
    Asa
    <small>Reforms Judah, trusts God to defeat Ethiopian army, enters covenant to seek God.</small>
    "]
    ---
    AsaBaasha["
    <small>Takes gold and silver from temple to gain support from Syria to thwart Baasha.</small>
    "]
    ---
    AsaHanani["
    <small>Confronted by Hanani, throws him in prison, inflicts cruelties on the people.</small>
    "]
    ---
    AsaFire["
    <small>Dies of disease in his feet, fire is made in his honor.</small>
    "]
    ---
    Jehoshaphat["
    Jehoshaphat
    <small>Walks in the way of David, teaches law of the Lord, strengthens Judah's army.</small>
    "]
    ---
    JehoshaphatAlliance["
    <small>Makes alliance with Ahab, agrees to capture Ramoth-gilead from Syria, doesn't listen to false prophets.</small>
    "]
    ---
    JehoshaphatSpared["
    <small>Dressed in his robes, spared in battle.</small>
    "]
    ---
    JehoshaphatCleanup["
    <small>Gets rid of the male cult prostitutes in Judah.</small>
    "]
    ---
    JehoshaphatJehu["
    <small>Prophet Jehu confronts him for helping Ahab, he appoints judges and makes reforms in Judah.</small>
    "]
    ---
    JehoshaphatMoabites["
    <small>Trusts in the Lord to defeat the Moabites, Ammonites, and Meunites.</small>
    "]
    ---
    JehoshaphatAhaziah["
    <small>Allies with Ahaziah to build ships, prophet Eliezer warns destruction, God wrecks the ships.</small>
    "]
    ---
    JehoshaphatJehoram["
    <small>Allies with Jehoram to defeat Moab.</small>
    "]
    ---
    Joram["
    Joram
    <small>Kills his six brothers, marries daughter of Ahab, leads people to idolatry, the Lord spares his house for David's sake.</small>
    "]
    ---
    JoramEdom["
    <small>Edom and Libnah revolt, Elijah prophesies plague and his death, Philistines and Arabians kill all but his youngest son Ahaziah.</small>
    "]
    ---
    JoramDeath["
    <small>Dies of disease in bowels, no fire in his honor, not buried with kings.</small>
    "]
    ---
    AhaziahJudah["
    Ahaziah
    <small>Mother is Athalia granddaughter of Omri, walks in the way of Ahab, allies with Jehoram to attack Syria.</small>
    "]
    ---
    AhaziahJudahFlees["
    <small>Flees from Jehu to Samaria where he is killed, buried in the city of David.</small>
    "]
    ---
    AhaziahAthalia["
    <small>Athalia takes over Judah and kills the royal family of the house of David, his sister Jehoshabeath, wife of priest Jehoiada, hides his son Joash in the temple.</small>
    "]
    ---
    Joash["
    Joash
    <small>Anointed by Jehoiada when he is 7, Jehoiada has Athalia killed and restores the priests and the temple, there is rejoicing and peace in Judah.</small>
    "]
    ---
    JoashCounsel["
    <small>Follows counsel of Jehoiada, does what is right in the eyes of the Lord, raises money to restore the temple.</small>
    "]
    ---
    JoashBadCounsel["
    <small>Jehoiada dies, follows bad counsel from princes, leads people to idolatry, takes sacred gifts and gold from temple to placate Syria.</small>
    "]
    ---
    JoashDeath["
    <small>Jehoiada's son Zechariah confronts the people, has him stoned in temple courts, defeated by Syrian army, assassinated by his servants, not buried with the kings.</small>
    "]
    ---
    Amaziah["
    Amaziah
    <small>Does what is right in the eyes of the Lord, but not with his whole heart, kills servants who killed his father.</small>
    "]
    ---
    AmaziahArmy["
    <small>Rallies army, hires Israelite soldiers, prophet warns him about Israelite soldiers, dismisses them and they raid Judah, defeats Edomites.</small>
    "]
    ---
    AmaziahEdomite["
    <small>Brings back Edomite gods and worships them, prophet rebukes him, threatens prophet, destruction is prophesied.</small>
    "]
    ---
    AmaziahCaptured["
    <small>Defeated and captured by Israel who breaks down wall in Jerusalem and plunders the temple and king's house.</small>
    "]
    ---
    AmaziahConspires["
    <small>Judah conspires against him, flees to Lachish where he is killed, buried in the city of David.</small>
    "]
    ---
    Uzziah["
    Uzziah
    <small>Does what is right in the eyes of the Lord, recovers land, defeats the Philistines, the Arabians, and the Meunites, strengthens army and cities, promotes farming, becomes famous.</small>
    "]
    ---
    UzziahBurn["
    <small>When he is strong, become prideful, tries to burn unauthorized incense in the temple, struck with leprosy, lives in separate house, his son Jotham governs the people.</small>
    "]
    ---
    UzziahDeath["
    <small>Dies and is buried in the king's field and not the royal tombs because of leprosy.</small>
    "]
    ---
    Jotham["
    Jotham
    <small>Does what is right in the eyes of the Lord, but high places remain, builds upper gate of temple, attacked by king of Syria and Pekah, king of Israel.</small>
    "]
    ---
    JothamAmmonites["
    <small>Defeats the Ammonites, becomes mighty by ordering his ways before the Lord.</small>
    "]
    ---
    Ahaz["
    Ahaz
    <small>Does what is evil in the sight of the Lord, walks in the way of Israel, burns his son as an offering, worships at high places.</small>
    "]
    ---
    AhazSyria["
    <small>Syria and Israel wage war on Judah, prophet Isaiah reminds him to have faith in God, gives silver and gold from temple to king of Assyria, Isaiah prophesies the birth of Immanuel and the exile by Assyria, Assyria takes Damascus, sees altar there and builds replica in temple.</small>
    "]
    ---
    AhazTemple["
    <small>Shuts temple doors and desecrates temple furnishings, claims bronze altar for himself.</small>
    "]
