graph TD
    ShalmeneserV["
    Shalmeneser V
    <em>Assyria</em>
    <small>727-722 BC</small>
    "]
    ---
    ShalmeneserV2["
    <small>722 BC</small>
    <small>Captures Samaria (Northern Israel) and exiles Israelites to Assyria.</small>
    "]
    ---
    NebuchadnezzarII["
    Nebuchadnezzar II
    <em>Babylon</em>
    <small>605-562 BC</small>
    "]
    ---
    NebuchadnezzarII2["
    <small>605 BC</small>
    <small>Besieges Jerusalem and begins taking Israelites to Babylon to educate them to gain political power. <b>Daniel</b> is taken to Babylon during this time. <b>Jeremiah</b> prophesies 70 years of captivity during this time.</small>
    "]
    ---
    NebuchadnezzarII3["
    <small>597 BC</small>
    <small>Captures Jerusalem and takes the first round of people into exile in Babylon including Judah's king <b>Jehoiachin</b>. <b>Ezekiel</b> is taken during this time.</small>
    "]
    ---
    NebuchadnezzarII4["
    <small>586 BC</small>
    <small>Destroys Jerusalem and takes a second round of people into exile in Babylon including Judah's king <b>Zedekiah</b>.</small>
    "]
    ---
    NebuchadnezzarII5["
    <small>582 BC</small>
    <small><b>Gedaliah</b>, his appointed governor of Judah, is assassinated and a third round of exiles go to Babylon.</small>
    "]
    ---
    EvilMerodach["
    Evil-merodach
    <em>Babylon</em>
    <small>562-560 BC</small>
    "]
    ---
    EvilMerodach2["
    <small>561 BC</small>
    <small>Releases <b>Jehoiachin</b> from prison.</small>
    "]
    ---
    Belshazzar["
    Belshazzar
    <em>Babylon</em>
    <small>556-539 BC</small>
    "]
    ---
    Belshazzar2["
    <small>539 BC</small>
    <small>Babylon falls to Persia. Realizing <b>Jeremiah's</b> prophecy of 70 years is almost complete, <b>Daniel</b> prays and God reveals to him that there will be 70 weeks until there will be an end to transgression and sin, atonement, and the anointing of a most holy place.</small>
    "]
    ---
    Cyrus["
    Cyrus
    <em>Persia</em>
    <small>559-530 BC</small>
    "]
    ---
    Cyrus2["
    <small>538 BC</small>
    <small>Makes decree to rebuild the temple, thus fulfilling <b>Jeremiah's</b> prophecy of 70 years of exile.</small>
    "]
    ---
    Darius["
    Darius
    <em>Persia</em>
    <small>552-486 BC</small>
    "]
    ---
    Darius2["
    <small>536 BC</small>
    <small>Stops the building of the temple based on a appeal from the people living in Samaria.</small>
    "]
    ---
    Darius3["
    <small>520 BC</small>
    <small><b>Haggai</b> and <b>Zechariah</b> prophesy, then <b>Zerubbabel</b> and <b>Jeshua</b> continue the temple construction. Darius allows this when he is reminded of Cyrus' decree.</small>
    "]
    ---
    Darius4["
    <small>515 BC</small>
    <small>The temple is finished and dedicated, the Passover is celebrated.</small>
    "]
    ---
    Xerxes["
    Xerxes
    <em>Persia</em>
    <small>486-465 BC</small>
    "]
    ---
    Xerxes2["
    <small>483 BC</small>
    <small><b>Esther</b> elevated to Queen. His second in command Haman plots to destroy all the Jews in Persia. <b>Mordecai</b> saves the king and is elevated to second in command. Haman is executed. The Jews defend themselves. The first Purim is celebrated.</small>
    "]
    ---
    Xerxes3["
    <small>480 BC</small>
    <small>Persians defeated by the outnumbered Greeks in the Battle of Salamis allowing Macedon to revolt against Persian rule.</small>
    "]
    ---
    Artaxerxes["
    Artaxerxes
    <em>Persia</em>
    <small>465-424 BC</small>
    "]
    ---
    Artaxerxes2["
    <small>458 BC</small>
    <small>Makes decree for Jews to return to Jerusalem, to provide further adornment of the temple, and for <b>Ezra</b> to establish the Mosaic law and to appoint judges.</small>
    "]
    ---
    Artaxerxes3["
    <small>Stops the rebuilding of Jerusalem based on a appeal from the people living in Samaria.</small>
    "]
    ---
    Artaxerxes4["
    <small>445 BC</small>
    <small>Allows <b>Nehemiah</b> to return to Jerusalem to rebuild the city's walls. Six months later, the wall is finished, its construction only taking 52 days.</small>
    "]
    ---
    AlexanderTheGreat["
    Alexander the Great
    <em>Greece</em>
    <small>336-323 BC</small>
    "]
    ---
    AlexanderTheGreat2["
    <small>334 BC</small>
    <small>Conquers Persia. Looks to spread Hellenism.</small>
    "]
    ---
    AlexanderTheGreat3["
    <small>323 BC</small>
    <small>Kingdom is divided among his four generals.</small>
    "]

    %% Ptolemies
    AlexanderTheGreat3
    ---
    PtolemyISoter["
    Ptolemy I Soter
    <em>Ptolemies - South - Egypt</em>
    <small>304-282 BC</small>
    "]
    ---
    PtolemyIIPhiladelphus["
    Ptolemy II Philadelphus
    <em>Ptolemies - South - Egypt</em>
    <small>284-246 BC</small>
    "]
    ---
    PtolemyIIPhiladelphus2["
    <small>250 BC</small>
    <small>Sends daughter to marry Antiochus II as a political move.</small>
    "]

    %% Seleucids
    AlexanderTheGreat3
    ---
    SeleucusINicator["
    Seleucus I Nicator
    <em>Seleucids - North - Syria</em>
    <small>305-281 BC</small>
    "]
    ---
    SeleucusINicator2["
    <small>250 BC</small>
    <small>Founds the city of Antioch which is named after his father Antiochus.</small>
    "]
    ---
    AntiochusIITheos["
    Antiochus II Theos
    <em>Seleucids - North - Syria</em>
    <small>261-246 BC</small>
    "]
    ---
    AntiochusIITheos2["
    <small>250 BC</small>
    <small>Wife poisons him and Ptolemy II's daughter who was sent to marry him.</small>
    "]

    %% Antiochus III
    AntiochusIIITheGreat["
    Antiochus III the Great
    <em>Seleucids - North - Syria</em>
    <small>222-187 BC</small>
    "]
    AntiochusIITheos2 --- AntiochusIIITheGreat
    PtolemyIIPhiladelphus2 --- AntiochusIIITheGreat
    ---
    AntiochusIIITheGreat2["
    <small>198 BC</small>
    <small>Spread of Hellenism continues. Turns temple into a pagan shrine, forbids worship and Jewish culture under penalty of death.</small>
    "]
    ---
    AntiochusIIITheGreat3["
    <small>188 BC</small>
    <small>Romans force him to sign a treaty and surrender territory, and his son Antiochus IV, he is forced to pay a large tribute to Rome, he returns home and attempts to pillage temple of Zeus and is killed by an angry mob.</small>
    "]
    ---
    SeleucusIVPhilopator["
    Seleucus IV Philopator
    <em>Seleucids - North - Syria</em>
    <small>187-175 BC</small>
    "]
    ---
    SeleucusIVPhilopator2["
    <small>178 BC</small>
    <small>Sent a tax collector to collect the money to pay Rome, his own tax collector poisons him, son is imprisoned in Rome.</small>
    "]
    ---
    %% THE Antiochus
    AntiochusIVEpiphanes["
    Antiochus IV Epiphanes
    <em>Seleucids - North - Syria</em>
    <small>175-164 BC</small>
    "]
    ---
    AntiochusIVEpiphanes2["
    <small>175 BC</small>
    <small>Uses bribery to take the throne when his nephew is imprisoned in Rome.</small>
    "]
    ---
    AntiochusIVEpiphanes3["
    <small>168 BC</small>
    <small>Invades Egypt but defeated by the Romans who were allied with the Ptolemies.</small>
    "]
    ---
    AntiochusIVEpiphanes4["
    <em>Antiochus Profanes the Temple</em>
    <small>167 BC</small>
    <small>Flees Egypt, sends tax collector to Jerusalem who kills and plunders the Jews on the Sabbath, promotes Hellenistic policies in Jerusalem, profanes the temple by stopping the offerings, setting up an idol of Zeus, and offering unclean animals.</small>
    "]
    ---
    AntiochusIVEpiphanes5["
    <em>Maccabean Revolt</em>
    <small><b>Mattathias</b> the priest (Hasmonean as his great grandfather was Hasmon from the house of Levi) and his family (5 sons, 3rd is <b>Judas Maccabeus</b>) refuse to worship Zeus at Modein (northwest of Jerusalem) while under Seleucid rule, they revolt (Maccabean Revolt) and attempt to restore the land.</small>
    "]
    ---
    AntiochusIVEpiphanes6["
    <em>Feast of the Dedication</em>
    <small>164 BC</small>
    <small>Dies while on campaign in Persia. Fighting ceases on the 25 of Kislev (December) and the first Feast of Lights (Hanukkah) is celebrated. <b>Judas</b> cleanses the temple. Regular worship is resumed.</small>
    "]
    ---
    HasmoneanPeriod["
    Hasmonean Period
    <small>164-63 BC</small>
    <small>The Maccabean rulers become progressively dictatorial, corrupt, immoral, and pagan.</small>
    "]
    ---
    HasmoneanPeriod2["
    General Pompey
    <small>63 BC</small>
    <small>Jewish leaders solicit the help of Roman General Pompey. Pompey brings about Roman rule. Pompey enters the temple and the Most Holy Place, profaning the temple. Roman oppression begins. Deep suspicion and ill will grows between the Jews and Romans. Rome begins removing and appointing priests at will.</small>
    "]

    %% Rome
    HasmoneanPeriod2
    ---
    CaesarAugustus["
    Caesar Augustus
    <em>Rome</em>
    <small>27 BC - 14 AD</small>
    "]
    ---
    CaesarAugustus2["
    <small>Makes a decree for everyone to be registered in their ancestral land. <b>St. Joseph</b> and <b>the Blessed Virgin Mary</b> go from Nazareth to Bethlehem. <b>Jesus</b> born in Bethlehem.</small>
    "]
    ---
    TiberiusCaesar["
    Tiberius Caesar
    <em>Rome</em>
    <small>14-37 AD</small>
    "]
    ---
    Caligula["
    Caligula
    <em>Rome</em>
    <small>37-41 AD</small>
    "]
    ---
    Caligula2["
    <small>37 AD</small>
    <small>Rebuilds the city of Antioch, the capital of the Roman province of Syria, after it had been devastated by an earthquake.</small>
    "]
    ---
    Claudius["
    Claudius
    <em>Rome</em>
    <small>41-54 AD</small>
    "]
    ---
    Claudius1["
    <small>The disciples are scattered due to persecution, and the Church, called The Way by some, starts to gain traction in the Gentile city of Antioch. <b>St. Barnabas</b> and <b>St. Paul</b> spend a year teaching there. It is at this time that people in Antioch begin calling the disciples Christians.</small>
    "]
    ---
    Claudius2["
    <small><b>Agabus</b>, a Christian prophet from Jerusalem, goes to Antioch and prophesies in the Holy Spirit that there will be a famine. The famine takes place, and the disciples led by <b>St. Barnabas</b> and <b>St. Paul</b> send relief to their brothers in Jerusalem.</small>
    "]
    ---
    Claudius3["
    <small>49 AD</small>
    <small>Expels the Jews from Rome due to a disturbance in the Jewish synagogues created by the Christian message.</small>
    "]
    ---
    Nero["
    Nero
    <em>Rome</em>
    <small>54-68 AD</small>
    "]
    ---
    Nero1["
    <small>64 AD</small>
    <small>He accuses Christians of starting the Great Fire of Rome and has them brutally executed, being thrown to beasts, crucified, and burned alive.</small>
    "]
    ---
    Nero2["
    <small>68 AD</small>
    <small><b>Saints Peter and Paul</b> are executed during his reign.</small>
    "]
    ---
    Titus["
    Titus
    <em>Rome</em>
    <small>79-81 AD</small>
    "]
    ---
    Titus1["
    <small>66 AD</small>
    <small>The Jews rebel against the Roman Empire in the First Jewish-Roman War (also called the Great Jewish Revolt).</small>
    "]
    ---
    Titus2["
    <em>Destruction of the Second Temple</em>
    <small>70 AD</small>
    <small>Roman legions under his command take and destroy the second temple.</small>
    "]
    ---
    Domitian["
    Domitian
    <em>Rome</em>
    <small>81-96 AD</small>
    "]
    ---
    Domitian2["
    <small>Heavily persecutes Jews and Christians towards the end of his reign. <b>St. John</b> is exiled from Ephesus to the island of Patmos and writes the Book of Revelation during this time.</small>
    "]

    %% Judea
    HasmoneanPeriod2
    ---
    HerodTheGreat["
    Herod the Great
    <em>Judea</em>
    <small>37-1 BC</small>
    "]
    ---
    HerodTheGreat2["
    <small>An Edomite appointed by the Roman senate. Maintains position by cooperating with Rome.</small>
    "]
    ---
    HerodTheGreat3["
    <em>The Holy Innocents</em>
    <small><b>St. Joseph</b> and <b>the Blessed Virgin Mary</b> take <b>Jesus</b> to Egypt to avoid him. Kills all the male children two and under in Bethlehem when he is unable to find Jesus.</small>
    "]
    ---
    HerodArchelaus["
    Herod Archelaus
    <em>Judea</em>
    <small>1 BC - 6 AD</small>
    "]
    ---
    HerodArchelaus2["
    <small><b>St. Joseph</b> and <b>the Blessed Virgin Mary</b> are called to return to Israel, and they take <b>Jesus</b> to Nazareth to avoid him because he is cruel to the Jews.</small>
    "]
    ---
    HerodArchelaus3["
    <small>6 AD</small>
    <small>He is deposed by Caesar Augustus.</small>
    "]
    ---
    PontiusPilate["
    Pontius Pilate
    <em>Judea</em>
    <small>26-36 AD</small>
    "]
    ---
    PontiusPilate2["
    <small>Kills Galileans who were trying to offer sacrifices.</small>
    "]
    ---
    PontiusPilate3["
    <em>The Crucifixion</em>
    <small>33 AD</small>
    <small>Delivers <b>Jesus</b> over to be crucified.</small>
    "]
    ---
    HerodAgrippa["
    Herod Agrippa
    <em>Judea</em>
    <small>41-44 AD</small>
    "]
    ---
    HerodAgrippa2["
    <small>Executes <b>St. James</b>.</small>
    "]
    ---
    HerodAgrippa3["
    <small>Throws <b>St. Peter</b> in prison during the passover. An angel frees Peter from prison, and when Herod can't find him, he kills the sentries who were guarding him.</small>
    "]
    ---
    HerodAgrippa4["
    <small>Looks to war with Tyre and Sidon who persuade his personal attendant to advocate for peace since they rely on food from Roman-controlled Judea.</small>
    "]
    ---
    HerodAgrippa5["
    <small>Goes to give a speech before Tyre and Sidon, and the people attempt to flatter him by treating him as a god. He pridefully accepts their flattery and glorifies himself, thus God strikes him down immediately.</small>
    "]
    ---
    HerodAgrippaII["
    Herod Agrippa II
    <em>Judea</em>
    <small>44-92 AD</small>
    "]
    ---
    HerodAgrippaII2["
    <small>57 AD</small>
    <small>The Jews accuse <b>St. Paul</b> of blasphemy. Paul is brought to Felix the governor of Palestine where he is imprisoned for two years.</small>
    "]
    ---
    HerodAgrippaII3["
    <small>60 AD</small>
    <small>Felix is removed from office for being unable to handle a dispute between the Jews and the Gentiles in Caesarea. He is succeeded by Festus.</small>
    "]

    %% Galilee
    HasmoneanPeriod2
    ---
    HerodAntipas["
    Herod Antipas
    <em>Galilee</em>
    <small>4 BC - 39 AD</small>
    "]
    ---
    HerodAntipas2["
    <small><b>St. John the Baptist</b> rebukes him for unlawfully marrying his sister-in-law. Throws John the Baptist in prison.</small>
    "]
    ---
    HerodAntipas3["
    <small>Conspires with the Pharisees to destroy <b>Jesus</b>.</small>
    "]
    ---
    HerodAntipas4["
    <small>Has <b>St. John the Baptist</b> executed at the request of his stepdaughter.</small>
    "]
