export const colors = {
  black: "var(--black)",
  white: "var(--white)",
  red: "var(--red)",
  pink: "var(--pink)",
  blue: "var(--blue)",
  grey: "var(--grey)",
  lightGrey: "var(--light-grey)",
  xLightGrey: "var(--x-light-grey)",
  darkGrey: "var(--dark-grey)",
  border: "var(--border)",
  ripple: "var(--ripple)",
  hover: "var(--hover)",
  hoverSolid: "var(--hover-solid)",
};
